# Generated by Django 2.2.3 on 2019-08-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='employer_status',
            field=models.CharField(default='applied', max_length=20, verbose_name='Application Status (for employer)'),
        ),
    ]
