# Generated by Django 2.2.3 on 2019-08-01 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_application_employer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_edited_by_employer',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 1, 16, 56, 43, 428829, tzinfo=utc), verbose_name='Last edited by employer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='employer_status',
            field=models.CharField(choices=[('applied', 'applied'), ('interview', 'interview'), ('rejected', 'rejected')], default='applied', max_length=20, verbose_name='Application Status (for employer)'),
        ),
    ]
