# Generated by Django 2.2.3 on 2019-08-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190801_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='last_edited_by_employer',
        ),
        migrations.AddField(
            model_name='job',
            name='manually_closed',
            field=models.BooleanField(default=False, verbose_name='Manually Closed'),
        ),
    ]
