# Generated by Django 2.2.3 on 2019-09-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0004_auto_20190802_1519")]

    operations = [
        migrations.AddField(
            model_name="application",
            name="draft",
            field=models.BooleanField(default=False, verbose_name="Draft"),
        )
    ]
