# Generated by Django 2.2.3 on 2019-10-26 17:38

from django.db import migrations
import s3upload.fields


class Migration(migrations.Migration):

    dependencies = [("api", "0005_application_draft")]

    operations = [
        migrations.RemoveField(model_name="applicationattachment", name="slug"),
        migrations.RemoveField(model_name="jobattachment", name="slug"),
        migrations.AlterField(
            model_name="application",
            name="cv",
            field=s3upload.fields.S3UploadField(dest="cv"),
        ),
        migrations.AlterField(
            model_name="applicationattachment",
            name="attachment",
            field=s3upload.fields.S3UploadField(dest="application_attachment"),
        ),
        migrations.AlterField(
            model_name="jobattachment",
            name="attachment",
            field=s3upload.fields.S3UploadField(dest="job_attachment"),
        ),
    ]
