# Generated by Django 2.2.3 on 2019-10-27 14:35

from django.db import migrations, models
import s3upload.fields


class Migration(migrations.Migration):

    dependencies = [("api", "0006_auto_20191026_1738")]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="cover_letter",
            field=models.TextField(null=True, verbose_name="Cover Letter"),
        ),
        migrations.AlterField(
            model_name="application",
            name="cv",
            field=s3upload.fields.S3UploadField(dest="cv", null=True),
        ),
        migrations.AlterField(
            model_name="application", name="date", field=models.DateTimeField()
        ),
    ]
