# Generated by Django 2.2.3 on 2019-12-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0008_auto_20191112_0649")]

    operations = [
        migrations.AddField(
            model_name="message",
            name="replied",
            field=models.BooleanField(default=False, verbose_name="Replied"),
        )
    ]
