# Generated by Django 2.2.3 on 2020-01-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0009_message_replied")]

    operations = [
        migrations.AlterModelOptions(name="message", options={"ordering": ("-date",)})
    ]
