# Generated by Django 2.2.3 on 2019-08-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telephone Number'),
        ),
    ]
