# Generated by Django 2.2.3 on 2019-08-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone Number'),
        ),
    ]
