# Generated by Django 2.2.3 on 2019-07-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190717_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Organization Name'),
        ),
    ]
