# Generated by Django 2.2.3 on 2019-08-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190803_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Telephone Number'),
        ),
    ]
