# Generated by Django 2.2.3 on 2020-01-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0004_auto_20190803_1607")]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="active", new_name="is_active"
        )
    ]
